### ISSUE TITLE
Use `defer` so that different subscribers don't share the same Subject

### ISSUE THREAD

**Issue by maxime1992** [bjoerge/rxjs-exhaustmap-with-trailing#1]
I read this comment on SO which was referring to the same thread on SO where I discovered your library.

I think this comment is legit and it'd be a good idea to use defer

https://stackoverflow.com/questions/63392119/how-to-create-a-joined-observable-which-exhausts-but-always-fires-the-very-last

And BTW thanks for extracting that into a library and testing it :pray:

**Comment by bjoerge** [comment]
Thanks for pointing out!

Using defer now in [v1.1.0](https://github.com/bjoerge/rxjs-exhaustmap-with-trailing/releases/tag/v1.1.0)
