### ISSUE TITLE
That has a bug

### ISSUE THREAD

**Issue by Lenic** [bjoerge/rxjs-exhaustmap-with-trailing#2]
This is a bug: 

``` js
import { fromEvent, of } from 'rxjs';
import { exhaustMapWithTrailing } from 'rxjs-exhaustmap-with-trailing';

const s1 = fromEvent(document, 'click').pipe(
  exhaustMapWithTrailing(v => of(v))
);

s1.subscribe(v => console.log('1', v));
```

This is a demo: https://stackblitz.com/edit/ryvcma?file=index.ts

**Comment by Lenic** [comment]
This is the fixed demo: https://stackblitz.com/edit/ryvcma-wil8x4?file=index.ts

**Comment by bjoerge** [comment]
Out of curiosity, what's the use case for having `exhaustMapWithTrailing` project to a sync value/emission?

Could this be solved for you by returning an async value in this case? 

```js
const s1 = fromEvent(document, 'click').pipe(
  exhaustMapWithTrailing(v => Promise.resolve(v))
);
```

**Comment by Lenic** [comment]
no case, that's my problem.
