### ISSUE TITLE
Throttle blocks on sync projected observable

### ISSUE THREAD

**Issue by maknapp** [bjoerge/rxjs-exhaustmap-with-trailing#4]
This is caused by: https://github.com/ReactiveX/rxjs/issues/5443

If the projected observable is synchronous, throttle will not see it and will continue to block.

Given the following example, if x is true EMPTY will run and block the inner throttle forever. When x becomes false, the timer observable will never run.
```typescript
exhaustMapWithTrailing((x) => x ? EMPTY : timer(1000));
```

Until the rxjs issue is fixed, a possible workaround is to force async by changing this line:
https://github.com/bjoerge/rxjs-exhaustmap-with-trailing/blob/05697095065402544fa965d2848747818ba1bdeb/index.ts#L31

with:
```typescript
scheduled(project(value, index), asyncScheduler).pipe(
```

**Comment by bjoerge** [comment]
Fixed & released in [v2.1.0](https://github.com/bjoerge/rxjs-exhaustmap-with-trailing/commit/57c492a53008209ee1d609f26ca3aaf5757d95b0) and [v1.2.0](https://github.com/bjoerge/rxjs-exhaustmap-with-trailing/releases/tag/v1.2.0)
