### ISSUE TITLE
Can rxjs v7.0.0 be supported?

### ISSUE THREAD

**Issue by zdu-strong** [bjoerge/rxjs-exhaustmap-with-trailing#6]
My project uses rxjs v7.5.6. There is a conflict when installing dependencies.
![image](https://user-images.githubusercontent.com/48673442/192175854-8d0ab51a-73f6-49e2-9e56-f06a75b5247f.png)

Can rxjs v7.x.x be supported?

**Comment by bjoerge** [comment]
rxjs@7 has been supported since [v2.0.0](https://github.com/bjoerge/rxjs-exhaustmap-with-trailing/releases/tag/v2.0.0). Upgrade to latest 2.x and it should work.
